### ISSUE TITLE
XT 使用中遇到的问题

### ISSUE THREAD

**Issue by errnull** [yyued/XT#2]

**Comment by errnull** [comment]
this.bgImageView.image = require('../assets/fitness_bg@2x.png')
代码中使用 require 会报错：[ts] 找不到名称“require”。

**Comment by errnull** [comment]
xt.d.ts 中本身包含了这个 declare
暂时没发现是什么问题，暂时先在对应的文件中加入
declare var require: (path: string) => any;
即可正常使用。

**Comment by PonyCui** [comment]
https://github.com/XTStudio/XT/commit/5f9b8f0bb91069f991ad7555f38502bb1b34c3e1
Fixed.
