### ISSUE TITLE
遇到的一些并非 issue 的使用上的问题

### ISSUE THREAD

**Issue by errnull** [yyued/XT#4]

**Comment by errnull** [comment]
1.API 智能提示容易混淆导致结果异常，但是没办法排查。
eg：
使用
this.bgImageView.contentMode = UI.ContentMode.ScaleAspectFit
【正常】
如果在输入 
<img width="1041" alt="2018-03-29 10 12 57" src="https://user-images.githubusercontent.com/28481578/38066256-c8528a04-3339-11e8-8976-a668c903a6cb.png">
直接打了 ContentMode 会智能提示，回车时候自动引入
import { ContentMode } from "xt-studio";
此时设置无效。
还有其他 API 同样有这个问题。

**Comment by PonyCui** [comment]
https://github.com/XTStudio/XT/commit/96d68607f63f6184b09a9f96c09704bbf6417350 Fixed
