### ISSUE TITLE
搭建界面的时候遇到的问题 [UIKit]

### ISSUE THREAD

**Issue by errnull** [yyued/XT#5]

**Comment by errnull** [comment]
1.viewController 使用 NavigationBar 遇到的问题：
    a.实际上，在使用 navigationBar 的情况下，设置 this.view 中的 subView 的 y 值为 0 的时候，
      subView 应该置顶，
    eg：
![2018-03-29 17 34 07](https://user-images.githubusercontent.com/28481578/38081774-6b13287e-3377-11e8-9706-304231ea4c5e.png)
   
    b.使用 navigationBar 的情况下，将 this.view 中的 subView y 值设置为 -64，
        会出现 subView 盖住 navigationBar 的情况。
![2018-03-29 17 01 17](https://user-images.githubusercontent.com/28481578/38079980-d3ae00e8-3372-11e8-9525-bfffc659d01b.png)

        this.view.sendSubviewToBack(this.bgImageView)
        this.view.bringSubviewToFront(this.navigationBar)
        均无效。
    c.占位，待验证

**Comment by PonyCui** [comment]
NavigationBar 层级始终为最高

**Comment by errnull** [comment]
viewController 使用 NavigationBar 遇到的问题：
navigationBar 的 translucent 为 true  的时候，
原点应该在（0，0）点
当设置NO的时候，原点坐标在（0，64）
<img width="752" alt="2018-04-02 11 41 24" src="https://user-images.githubusercontent.com/28481578/38182286-063e37da-366b-11e8-856f-46c003c4ae6b.png">
