### ISSUE TITLE
iOS 客户端 API 实现问题

### ISSUE THREAD

**Issue by errnull** [yyued/XT#7]

**Comment by errnull** [comment]
1.iOS 设备访问 UI.Image 异常，但是图片能正常显示
<img width="694" alt="2018-03-30 17 37 58" src="https://user-images.githubusercontent.com/28481578/38133273-2345e87c-3441-11e8-9c93-f9d50e8d6142.png">
<img width="806" alt="2018-03-30 17 38 04" src="https://user-images.githubusercontent.com/28481578/38133277-25661406-3441-11e8-85d0-cd675cee6410.png">

**Comment by PonyCui** [comment]
https://github.com/XTStudio/XT/commit/47915157ce6d0022b9e1fbeffefa55a5341d1fb5 Fixed
