### ISSUE TITLE
[iOS 端] Navigationbar translucent 相关

### ISSUE THREAD

**Issue by errnull** [yyued/XT#9]

**Comment by errnull** [comment]
navigationBar.translucent 如果是 true，
原点在（0，0）
如果是 false，
原点坐标在（0，64）
<img width="752" alt="2018-04-02 11 41 24" src="https://user-images.githubusercontent.com/28481578/38182441-108a669a-366c-11e8-9706-c46dc9173aaa.png">

**Comment by PonyCui** [comment]
本来就是这样的
